services:
  fetcher:
    build: ./fetcher/chall
    container_name: ctf-fetcher
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG_FETCHER}

  nslookup:
    build: ./nslookup/chall
    container_name: ctf-nslookup
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG_NSLOOKUP}

  gag-wiki:
    build: ./gag-wiki/chall
    container_name: ctf-gagwiki
    ports:
      - "5002:5002"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG_GAGWIKI}

  svg-viewer:
    build: ./svg-viewer/chall
    container_name: ctf-svgviewer
    ports:
      - "8888:80"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG_SVG_VIEWER}
    command: /bin/sh -c "echo $$FLAG > /flag.txt && apache2-foreground"

  passforge:
    build: ./passforge/chall
    container_name: ctf-passforge
    ports:
      - "8120:8120"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG_PASSFORGE}
      - PROOF=${PROOF_PASSFORGE}
    command: /bin/sh -c "echo $$FLAG > /flag.txt && echo $$PROOF > /proof.txt && python service.py"

  papermaker:
    build: ./papermaker/chall
    container_name: ctf-papermaker
    ports:
      - "8130:8130"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG_PAPERMAKER}
    command: /bin/sh -c "echo $$FLAG > /flag.txt && bundle exec rackup --host 0.0.0.0 -p 8130"

  archivedesk:
    build: ./archivedesk/chall
    container_name: ctf-archivedesk
    ports:
      - "8150:8150"
    environment:
      - PORT=8150
      - FLAG=${FLAG_ARCHIVEDESK}
    restart: unless-stopped

  betorganizer:
    build: ./betorganizer/chall
    container_name: ctf-betorganizer
    ports:
      - "8140:8140"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG_BETORGANIZER}
    command: /bin/sh -c "echo $$FLAG > /flag.txt && ./betorganizer"

  action-packed:
    build: ./action-packed/chall
    container_name: ctf-action-packed
    ports:
      - "8160:8160"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG_ACTION_PACKED}

  silent-oracle:
    build: ./silent-oracle/chall
    container_name: ctf-silent-oracle
    ports:
      - "8170:8170"
    restart: unless-stopped
    environment:
      - FLAG=${FLAG_SILENT_ORACLE}

  resetter:
    image: docker:cli
    container_name: ctf-resetter
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./:/challenge
    working_dir: /challenge
    command: /bin/sh game_server.sh
    restart: unless-stopped
